#!/bin/bash

# Unduh source
curl https://codeload.github.com/raniaamina/libreoffice-theme/zip/master --output libreoffice-theme.zip
unzip libreoffice-theme.zip && cd libreoffice-theme-master
mkdir -p ~/.config/libreoffice/4/user/gallery/personas/LibreOffice-Light-Ambiance



# Salin tema Persona ke Gallery
cp img/footer.png ~/.config/libreoffice/4/user/gallery/personas/LibreOffice-Light-Ambiance/footer.png
cp img/header.png ~/.config/libreoffice/4/user/gallery/personas/LibreOffice-Light-Ambiance/header.png
cp img/preview.png ~/.config/libreoffice/4/user/gallery/personas/LibreOffice-Light-Ambiance/preview.png
mv ~/.config/libreoffice/4/user/registrymodifications.xcu ~/.config/libreoffice/4/user/registrymodifications.xcu.backup
cp registrymodifications.xcu ~/.config/libreoffice/4/user/registrymodifications.xcu

# Salin berkas tema zip ke folder LO

OPTDIR=(`ls /opt | grep libreoffice`)
if [[ -n $OPTDIR ]]
then
    for ITEM in ${OPTDIR[@]}
    do
        sudo cp images_office2013.zip /opt/$ITEM/share/config/images_office2013.zip
        sudo mv /opt/$ITEM/program/intro.png /opt/$ITEM/program/intro.png.backup
        sudo cp img/intro.png /opt/$ITEM/program/intro.png
	sudo mv /opt/$ITEM/program/sofficerc /opt/$ITEM/program/sofficerc.backup
        sudo cp sofficerc /opt/$ITEM/program/sofficerc
    done
else
    sudo cp images_office2013.zip /usr/lib/libreoffice/share/config/images_office2013.zip
    sudo mv /usr/lib/libreoffice/share/program/intro.png /usr/lib/libreoffice/share/program/intro.png.backup
    sudo cp img/intro.png /usr/lib/libreoffice/share/program/intro.png
    sudo mv /usr/lib/libreoffice/share/program/sofficerc /usr/lib/libreoffice/share/program/sofficerc.backup
    sudo cp sofficerc /usr/lib/libreoffice/share/program/sofficerc
fi

cd ..
rm libreoffice-theme.zip
rm -rf libreoffice-theme-master


